print("============PILIH MENU========")
print("1.Tambah")
print("2.Kurang")
print("3.Kali")
print("4.Bagi")
billpertama = int(input("Masukan Angka Pertama:"))
billkedua = int(input("Masukan Angka Kedua:"))
print ("pilihan anda:1")
print("hasil", billpertama+billkedua)

print("============PILIH MENU========")
print("1.Tambah")
print("2.Kurang")
print("3.Kali")
print("4.Bagi")
billpertama = int(input("Masukan Angka Pertama:"))
billkedua = int(input("Masukan Angka Kedua:"))
print ("pilihan anda:2")
print("hasil", billpertama-billkedua)

print("============PILIH MENU========")
print("1.Tambah")
print("2.Kurang")
print("3.Kali")
print("4.Bagi")
billpertama = int(input("Masukan Angka Pertama:"))
billkedua = int(input("Masukan Angka Kedua:"))
print ("pilihan anda:3")
print("hasil", billpertama*billkedua)

print("============PILIH MENU========")
print("1.Tambah")
print("2.Kurang")
print("3.Kali")
print("4.Bagi")
billpertama = int(input("Masukan Angka Pertama:"))
billkedua = int(input("Masukan Angka Kedua:"))
print ("pilihan anda:4")
print("hasil", billpertama/billkedua)




